apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-eks-frontend
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/mmije0ng/Rookies_Terraform-k8s-infra'
    targetRevision: HEAD
    # 리포지토리 내의 매니페스트 파일 경로 (루트 폴더일 경우 '.')
    path: 'manifests/frontend'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true